micronaut:
  application:
    name: expenshare
  server:
    port: 8080

datasources:
  default:
    url: jdbc:h2:mem:expenshare;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2
    schema-generate: CREATE_DROP   # for dev: creates schema at startup, drops at shutdown

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update            # or "create-drop" during development
        show_sql: true            # log SQL queries to console
        format_sql: true

kafka:
#  topics:
#    userCreated: user.created
#    groupCreated: group.created
#    notificationWelcome: notification.welcome
#    expenseAdded: expense.added
#    settlementConfirmed: settlement.confirmed
#    balanceReminder: balance.reminder
  producer:
    acks: all
    retries: 3
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
  bootstrap:
    servers: localhost:9092
